[versions]
kotlin = "2.2.21"
ktor = "3.3.2"
serialization = "1.9.0"

[libraries]
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-xml = { module = "io.github.pdvrieze.xmlutil:serialization", version = "0.91.3" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }

ktor-serialization-kotlinx-xml = { module = "io.ktor:ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

logback = { module = "ch.qos.logback:logback-classic", version = "1.5.20" }

dokka-mermaid = { module = "com.glureau:html-mermaid-dokka-plugin", version = "0.6.0" }

spring-bom = { module = "org.springframework.boot:spring-boot-dependencies", version = "3.5.7" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
serviceloader = { id = "app.softwork.serviceloader-compiler", version = "0.0.21" }
validation = { id = "app.softwork.validation", version = "0.0.15" }
mavencentral = { id = "io.github.hfhbd.mavencentral", version = "0.0.23" }
foojay = { id = "org.gradle.toolchains.foojay-resolver-convention", version = "1.0.0" }
