package com.example

import kotlin.String
import kotlinx.serialization.Serializable

/**
 * Represent a container for the Url where the results can be downloaded.
 */
@Serializable
public data class UrlContainer(
  /**
   * URL for the content generated by a Synchronisation Run
   */
  public val url: String,
)
