ktlint:
  ChainMethodContinuation:
    active: false
  FunctionSignature:
    active: false
  MaximumLineLength:
    active: false
  MultilineExpressionWrapping:
    active: false
  NoEmptyFirstLineInClassBody:
    active: true
  SpacingAroundSquareBrackets:
    active: true
  StringTemplateIndent:
    active: false

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'

style:
  CollapsibleIfStatements:
    active: true
  DataClassShouldBeImmutable:
    active: true
