name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Build with Gradle
        run: ./gradlew build
      - name: Build with Gradle
        run: ./gradlew :gradle-plugin:integrationTest
      - name: Build with Gradle
        run: ./gradlew :gradle-feature:integrationTest

      - name: Detekt
        run: ./gradlew :mergeDetektSarif
        if: always()
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt

      - name: Create baseline to upload suppressed code-smells to GitHub
        run: ./gradlew deleteDetektBaseline :mergeDetektSarif -PignoreDetektFailures=true
      - name: Upload detekt baseline to Github
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detektBaseline
