name: Snapshots

on:
  push:
    branches: [ main ]

jobs:
  publishMavenCentral:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    environment:
      name: mavenCentral

    steps:
      - name: Set environment for version
        uses: hfhbd/actions/setup-version@main
        id: version
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4

      - name: Release maven artifacts
        run: ./gradlew publishAllPublicationsToMavenCentralSnapshotRepository -Pversion=${{ steps.version.outputs.version }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralSnapshotUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralSnapshotPassword: ${{ secrets.CENTRAL_PASSWORD }}

  publishGitHubPackages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment:
      name: GPR

    steps:
      - name: Set environment for version
        uses: hfhbd/actions/setup-version@main
        id: version
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4

      - name: Release maven artifacts
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository -Pversion=${{ steps.version.outputs.version }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ github.token }}
