<?xml version='1.0' encoding='UTF-8' ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="https://schema.gradle.org/dependency-verification"
        xmlns="https://schema.gradle.org/dependency-verification"
>
    <xs:complexType name="coordinatesType">
        <xs:attribute name="group" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="version" type="xs:string"/>
        <xs:attribute name="regex" type="xs:boolean"/>
        <xs:attribute name="file" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="trustType">
        <xs:complexContent>
            <xs:extension base="coordinatesType">
                <xs:attribute name="reason" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="trusted-artifactsType">
        <xs:sequence>
            <xs:element name="trust" type="trustType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ignored-keyType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="reason" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="ignored-keysType">
        <xs:sequence>
            <xs:element name="ignored-key" type="ignored-keyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="trusted-keyType" mixed="true">
        <xs:sequence>
            <xs:element name="trusting" type="trustingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="group" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="version" type="xs:string"/>
        <xs:attribute name="file" type="xs:string"/>
        <xs:attribute name="regex" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="trustingType">
        <xs:complexContent>
            <xs:extension base="coordinatesType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="trusted-keysType">
        <xs:sequence>
            <xs:element name="trusted-key" type="trusted-keyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="key-serversType">
        <xs:sequence>
            <xs:element name="key-server" type="key-serverType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="key-serverType">
        <xs:attribute name="uri" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="configurationType">
        <xs:sequence>
            <xs:element name="verify-metadata" type="xs:boolean"/>
            <xs:element name="verify-signatures" type="xs:boolean"/>
            <xs:element name="keyring-format" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="armored"/>
                        <xs:enumeration value="binary"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="key-servers" type="key-serversType" minOccurs="0"/>
            <xs:element name="trusted-artifacts" type="trusted-artifactsType" minOccurs="0"/>
            <xs:element name="ignored-keys" type="ignored-keysType" minOccurs="0"/>
            <xs:element name="trusted-keys" type="trusted-keysType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="md5Type" mixed="true">
        <xs:sequence>
            <xs:element name="also-trust" type="also-trustType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="origin" type="xs:string"/>
        <xs:attribute name="reason" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="sha1Type" mixed="true">
        <xs:sequence>
            <xs:element name="also-trust" type="also-trustType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="origin" type="xs:string"/>
        <xs:attribute name="reason" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="sha256Type" mixed="true">
        <xs:sequence>
            <xs:element name="also-trust" type="also-trustType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="origin" type="xs:string"/>
        <xs:attribute name="reason" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="sha512Type" mixed="true">
        <xs:sequence>
            <xs:element name="also-trust" type="also-trustType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="origin" type="xs:string"/>
        <xs:attribute name="reason" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="pgpType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="value" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="artifactType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="sha512" type="sha512Type"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="componentType">
        <xs:sequence>
            <xs:element name="artifact" type="artifactType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="group" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="also-trustType">
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="componentsType">
        <xs:sequence>
            <xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="verification-metadataType">
        <xs:sequence>
            <xs:element name="configuration" type="configurationType"/>
            <xs:element name="components" type="componentsType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="verification-metadata" type="verification-metadataType"/>
</xs:schema>
